### PR TITLE
modified virus hash database

### PR DESCRIPTION
**Pull request by moongazer07**
added rickroll forkbomb virus hash to hash db
virus sample for analisys
password for zip is 12345
[rickastley.zip](https://github.com/anic17/Batch-Antivirus/files/7908830/rickastley.zip)

### CODE REVIEW

**Comment by anic17** [comment]
I will merge the pull request, but the hashes have to be lowercase to have a faster indexation. All hashes are case-sensitive so it's faster for `findstr.exe` to find.

**Comment by moongazer07** [comment]
python

**Comment by anic17** [comment]
> python

??

**Comment by K9-Software** [comment]
ok

**Pull request merged**
